name: http_security_pinning
description: An implementation of Dart's HttpClient with certificate pinning against SPKI hashes.
version: 1.2.2
repository: https://github.com/CaoGiaHieu-dev/http_security_pinning

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.27.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  asn1lib: ^1.6.5
  crypto: ^3.0.6
  cryptography: ^2.7.0
  http: ^1.2.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.hieucg.http_security_pinning
        pluginClass: HttpSecurityPinningPlugin
      ios:
        pluginClass: HttpSecurityPinningPlugin
      macos:
        dartPluginClass: HttpSecurityPinningPlugin
      linux:
        dartPluginClass: HttpSecurityPinningPlugin
      windows:
        dartPluginClass: HttpSecurityPinningPlugin
      web:
        pluginClass: HttpSecurityPinningWeb
        fileName: src/web/web_plugin_registrar.dart

false_secrets:
  - /test/fixtures/*.key
